repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: []
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        stages: [pre-push]
        pass_filenames: false
      - id: pytest-push
        name: pytest
        entry: uv run pytest -q -x
        language: system
        types: [python]
        stages: [pre-push]
        pass_filenames: false
