name: ci
on:
  push:
    paths-ignore: ['**.md']
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: uv sync --all-groups --frozen
      - run: uv run pre-commit run check-toml --all-files
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run pyright
      - run: uv run pytest --cov --cov-fail-under=80 --cov-report=xml --cov-report=term-missing
      - run: uv run coverage report --format=markdown --show-missing --skip-covered >> "$GITHUB_STEP_SUMMARY"
      - run: uvx vulture tidal2ytm --min-confidence 80
        continue-on-error: true
